### ISSUE TITLE
comment on calcule les recettes avec notre solution ?

### ISSUE THREAD

**Issue by sagarion** [abzak/ArcTransportCCT#4]
la méthode de calcule de la recette d'une course est la suivante : prix Voiture X km parcourus + taxe mais en fait selon notre système l'objet course ne connait plus l'objet voiture auquel il est lié. Seul la voiture connait ces courses.
Le problème réside au fait que l'on ne peut plus calculer le chiffre d'affaire d'un chauffeur directement.

Il faudrait pour chaque objet course d'un chauffeur allez rechercher dans voiture celle qui lui corresponds ... ?

**Comment by abzak** [comment]
Rajouter prix dans la course qui est calculer lors de sa création en fonction du prixMinute .
